<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ManageRoles.aspx.cs" Inherits="SsdMS.Admin.ManageRoles" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
        
        <div class="col-md-5">
            <h3>添加权限</h3>
            <dl class="dl-horizontal">
                <dt><asp:TextBox runat="server" ID="txtAddRole" CssClass="form-control"></asp:TextBox></dt>        
                <dd><asp:Button runat="server" ID="btAddRole" Text="添加" CssClass="btn btn-primary" OnClick="btAddRole_Click" /></dd>
            </dl>
            <p><asp:Label runat="server" ID="lblAddRole"></asp:Label></p>
         </div>
        
        <div class="col-md-7">
            <h3>删除权限</h3>
            <asp:GridView runat="server" ID="gdDeleteRoles" AutoGenerateColumns="false" DataKeyNames="Id"
                CssClass="table table-hover"
                AutoGenerateDeleteButton ="true" OnRowDeleting="gdDeleteRoles_RowDeleting">
                <Columns>
                    <asp:BoundField DataField="Name" HeaderText="权限名称"/>
                </Columns>
            </asp:GridView>
            <asp:Label runat="server" ID="lblDeleteRole"></asp:Label>
        </div>
</asp:Content>
