<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ManageDepartment.aspx.cs" Inherits="SsdMS.HR.ManageDepartment" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="col-md-5">
            <h3>添加科室</h3>
            <dl class="dl-horizontal">
                <dt><asp:TextBox runat="server" ID="txtAdd" CssClass="form-control"></asp:TextBox></dt>        
                <dd><asp:Button runat="server" ID="btAdd" Text="添加" CssClass="btn btn-primary" OnClick="btAdd_Click" /></dd>
            </dl>
            <p><asp:Label runat="server" ID="lblAdd"></asp:Label></p>
         </div>
        
        <div class="col-md-7">
            <h3>删除科室</h3>
            <asp:GridView runat="server" ID="gdDelete" ItemType="SsdMS.Models.Department" AutoGenerateColumns="false" DataKeyNames="Id"
                CssClass="table table-hover"
                AutoGenerateDeleteButton ="true" OnRowDeleting="gdDelete_RowDeleting">
                <Columns>
                    <asp:BoundField DataField="Name" HeaderText="权限名称"/>
                </Columns>
            </asp:GridView>
            <asp:Label runat="server" ID="lblDelete"></asp:Label>
        </div>
</asp:Content>
